/**
 * Temporary server-side storage for an upload session.
 *
 * Milestone 1 keeps this dead simple: photos land in a per-session directory
 * under the OS temp dir, with a `meta.json` alongside them. Nothing is kept in
 * process memory, so the dev server can hot-reload mid-session without losing
 * the upload. Anything here is disposable — the OS reaps it, and there is no
 * cleanup story yet (that's a real-storage problem for a later milestone).
 */

import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import type { PhotoMeta } from "./scoring";

const ROOT = path.join(tmpdir(), "photo-picker-uploads");

/** Ids are generated by us, but they arrive back over the wire — validate. */
const SAFE_ID = /^[a-zA-Z0-9_-]{1,64}$/;

export type SessionData = {
  sessionId: string;
  createdAt: string;
  photos: PhotoMeta[];
  /** Set once the client says the upload is complete. */
  finalized: boolean;
};

/**
 * Scoring is not done here. It needs the decoded pixels, and those live in the
 * browser — see `lib/analysis/`. This module is the storage half of the
 * server-side upload path, kept working behind NEXT_PUBLIC_UPLOAD_TO_SERVER
 * for when scoring moves server-side.
 */

function assertSafeId(id: string): string {
  if (!SAFE_ID.test(id)) throw new Error(`Invalid id: ${id}`);
  return id;
}

function sessionDir(sessionId: string): string {
  return path.join(ROOT, assertSafeId(sessionId));
}

function metaPath(sessionId: string): string {
  return path.join(sessionDir(sessionId), "meta.json");
}

export function photoPath(sessionId: string, photoId: string): string {
  return path.join(sessionDir(sessionId), assertSafeId(photoId));
}

export async function readSession(sessionId: string): Promise<SessionData | null> {
  try {
    const raw = await readFile(metaPath(sessionId), "utf8");
    return JSON.parse(raw) as SessionData;
  } catch {
    return null;
  }
}

async function writeSession(data: SessionData): Promise<void> {
  await writeFile(metaPath(data.sessionId), JSON.stringify(data, null, 2), "utf8");
}

/**
 * Appends a batch of files to a session, creating it if needed.
 *
 * The client uploads batches strictly sequentially, so the read-modify-write of
 * `meta.json` here is safe. If batches are ever parallelized, this needs a lock.
 */
export async function appendPhotos(
  sessionId: string,
  files: File[],
): Promise<SessionData> {
  const dir = sessionDir(sessionId);
  await mkdir(dir, { recursive: true });

  const session: SessionData = (await readSession(sessionId)) ?? {
    sessionId,
    createdAt: new Date().toISOString(),
    photos: [],
    finalized: false,
  };

  for (const file of files) {
    const id = `p${String(session.photos.length).padStart(4, "0")}_${randomSuffix()}`;
    const bytes = Buffer.from(await file.arrayBuffer());
    await writeFile(photoPath(sessionId, id), bytes);
    session.photos.push({
      id,
      name: file.name || `${id}.jpg`,
      type: file.type || "image/jpeg",
      size: bytes.byteLength,
    });
  }

  await writeSession(session);
  return session;
}

export async function finalizeSession(sessionId: string): Promise<SessionData> {
  const session = await readSession(sessionId);
  if (!session) throw new Error(`Unknown session: ${sessionId}`);
  session.finalized = true;
  await writeSession(session);
  return session;
}

export async function deleteSession(sessionId: string): Promise<void> {
  const dir = sessionDir(sessionId);
  if (existsSync(dir)) await rm(dir, { recursive: true, force: true });
}

export async function listSessions(): Promise<string[]> {
  try {
    return await readdir(ROOT);
  } catch {
    return [];
  }
}

function randomSuffix(): string {
  return Math.random().toString(36).slice(2, 8);
}
